### ISSUE TITLE
This plugin disables DokuWiki 2020-07-29 "Hogfather" to work.

### ISSUE THREAD

**Issue by EmmanuelChanel** [dokufreaks/plugin-linkback#17] opened 2022-01-30 08:10 UTC
I really want to put the linkback function on my DokuWiki 2020-07-29 "Hogfather" But this plugin disables it to work. When I installed it, my dokuwiki shows just a white page.

**Comment by splitbrain** [comment] 2022-01-30 08:34
please provide the actual error message from your logs

**Comment by EmmanuelChanel** [comment] 2022-01-30 11:57
The error log is like this:
> [Sun Jan 30 20:54:48.073722 2022] [php7:warn] [pid 3176526] [client 192.168.14.2:45890] PHP Warning:  require_once(/home/httpd/dokuwiki/inc/events.php): failed to open stream: No such file or directory in /home/httpd/dokuwiki/lib/plugins/linkback/action/display.php on line 21, referer: https://wiki.emmanuelchanel.com/start?do=admin&page=extension&tab=search&q=
> [Sun Jan 30 20:54:48.083867 2022] [php7:error] [pid 3176526] [client 192.168.14.2:45890] PHP Fatal error:  require_once(): Failed opening required '/home/httpd/dokuwiki/inc/events.php' (include_path='.:/usr/share/php') in /home/httpd/dokuwiki/lib/plugins/linkback/action/display.php on line 21, referer: https://wiki.emmanuelchanel.com/start?do=admin&page=extension&tab=search&q=
> [Sun Jan 30 20:54:48.210608 2022] [php7:warn] [pid 3176527] [client 192.168.14.2:45892] PHP Warning:  require_once(/home/httpd/dokuwiki/inc/events.php): failed to open stream: No such file or directory in /home/httpd/dokuwiki/lib/plugins/linkback/action/display.php on line 21, referer: https://wiki.emmanuelchanel.com/start?do=admin&page=extension&tab=search&q=Linkback
> [Sun Jan 30 20:54:48.210659 2022] [php7:error] [pid 3176527] [client 192.168.14.2:45892] PHP Fatal error:  require_once(): Failed opening required '/home/httpd/dokuwiki/inc/events.php' (include_path='.:/usr/share/php') in /home/httpd/dokuwiki/lib/plugins/linkback/action/display.php on line 21, referer: https://wiki.emmanuelchanel.com/start?do=admin&page=extension&tab=search&q=Linkback

**Comment by Klap-in** [comment] 2022-01-30 22:58
Please note that there is already a first proposal for improvements.
This needs still testing and updating of the parts in the exe/ folder. Help is welcome.

**Comment by Klap-in** [comment] 2022-01-30 22:59
Duplicate of #15

**Comment by drbeco** [comment] 2022-02-23 02:38
> please provide the actual error message from your logs

I would like to join the help, by providing a log if still needed. Please, where can I find the error log from this issue?

**Comment by Klap-in** [comment] 2022-08-03 18:11
Recent update should fix this and other minor issues.

@drbeco @EmmanuelChanel could you please test? (just use 'reinstall' in the Extension manager)

**Comment by EmmanuelChanel** [comment] 2022-08-03 19:03
Well, I tried installing the latest via git fist and via 'reinstall' after that. 
Now I don't find the issued error.
On the upper part, https://www.dokuwiki.org/plugin:linkback says that Last updated on 2021-12-27 , though. plug.info.txt is like this and my dokuwiki works.
----
$ cat plugin.info.txt
base   linkback
author Michael Hamann, Gina Häußge
email  michael@content-space.de
date   2022-08-03
name   Linkback plugin
desc   Adds Trackback and Pingback support to DokuWiki
url    https://dokuwiki.org/plugin:linkback

**Comment by Klap-in** [comment] 2022-08-03 19:26
Thanks!

**Closed by Klap-in** 2022-08-03 19:26 UTC

**Comment by drbeco** [comment] 2022-10-15 23:41
I've successfully installed it today. I'll report back in case of any future failures. But it looks like it is just fine now. 

Thanks for your upgrade on the matter @Klap-in
